include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 1Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 2

default:
  interruptible: true

stages:
  - lint
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

eslint:
  image: node:16-alpine
  stage: lint
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint

build-img-dev:
  extends: .build-image-using-kaniko
  stage: build
  variables:
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    NEXT_PUBLIC_NEXUS_TOKEN: $NEXUS_AUTH_TOKEN
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    NEXT_PUBLIC_BASE_PATH: /hippocampus-portal-dev
    NEXT_PUBLIC_STATIC_DATA_BASE_URL: /hippocampus-portal-dev/data
    CI_REGISTRY_IMAGE: $CI_REGISTRY/nse/hippocampus-model-portal
    REGISTRY_IMAGE_TAG: dev-$CI_COMMIT_SHORT_SHA-$(date +%s)
    CI_PROJECT_DIR: /builds/nse/hippocampus-model-portal
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_NEXUS_TOKEN
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_STATIC_DATA_BASE_URL
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_CPU_LIMIT: 2
  only:
  - develop
