import React from 'react';

import FullPage from '../layouts/FullPage';

import styles from '../styles/cookies-policy.module.scss';




export default function CookiesPolicyPage() {
  return (
    <FullPage>
      <div className="iq__container">
        <h1>COOKIES POLICY</h1>

        <p>
          Blue Brain Project’s (“<strong>BBP</strong>”) use of Cookies on the Hippocampus Hub - Home page and
          Hippocampus Hub – Explore Model Section (“<strong>Hub</strong>”).
        </p>

        <ul>
          <li>
            BBP Hub and online services may use “cookies.”
            Cookies are small text files placed on the hard drive of your device.
          </li>
          <li>
            There are several types of cookies: Session cookies are temporary bits of information
            that are erased once you exit your web browser window or otherwise turn your computer off.
            Persistent cookies remain on your computer until you delete them or they expire.
          </li>
        </ul>

        <h2>
          Which cookies are generated by BBP?
        </h2>

        <p>
          When you access BBP Hub, we can, according to your settings, install cookies on your devices,
          which will allow us to recognize your browser, during the validity time of the cookies.
          The cookies that BBP generates allow us:
        </p>

        <ul>
          <li>
            to prepare statistics including frequency of access, the use and performances of websites
          </li>
          <li>
            to adapt the presentation of BBP Hub to the display preferences of your device (language, operating system etc.)
          </li>
          <li>
            to improve our communication and services
          </li>
        </ul>

        <h2>How to control cookies?</h2>

        <p>
          Most web browsers automatically accept cookies but provide controls that allow you to block or delete them.
        </p>

        <p>
          Please refer to your browser’s privacy or help documentation
          to find Instructions for blocking or deleting cookies.
        </p>

        <p>
          If you choose to refuse cookies, you may not have access to certain functionality on the BBP Hub,
          which BBP cannot be held responsible for.
        </p>
      </div>
    </FullPage>
  );
}
